### ISSUE TITLE
Overriding the Raven app creating an issue

### ISSUE THREAD

**Issue by nilpatel42** [The-Commit-Company/raven#1028]
When we run this command `bench get-app https://github.com/The-Commit-Company/Raven.git`. we already have the raven app, it ask for override and we say Yes and this error shows

```
bench get-app https://github.com/The-Commit-Company/Raven.git
A directory for the application 'Raven' already exists. Do you want to continue and overwrite it? [y/N]: y
INFO: App moved from apps/Raven to archived/apps/Raven-2024-08-19
Getting Raven
$ git clone https://github.com/The-Commit-Company/Raven.git  --depth 1 --origin upstream
Cloning into 'Raven'...
remote: Enumerating objects: 678, done.
remote: Counting objects: 100% (678/678), done.
remote: Compressing objects: 100% (578/578), done.
remote: Total 678 (delta 97), reused 429 (delta 60), pack-reused 0 (from 0)
Receiving objects: 100% (678/678), 5.47 MiB | 3.42 MiB/s, done.
Resolving deltas: 100% (97/97), done.


ERROR: [Errno 39] Directory not empty: '/home/user/frappe-bench/apps/Raven' -> '/home/user/frappe-bench/apps/raven'
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 777, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 247, in install
    app_name = get_app_name(self.bench.name, self.app_name)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/app.py", line 253, in get_app_name
    os.rename(os.path.join(apps_path, folder_name), os.path.join(apps_path, app_name))
OSError: [Errno 39] Directory not empty: '/home/user/frappe-bench/apps/Raven' -> '/home/user/frappe-bench/apps/raven'
```

**Comment by nikkothari22** [comment]
I think this has to do with the name of the app being "raven" and the GitHub repo being "Raven". If we change the URL now, it might break something.

**Comment by nikkothari22** [comment]
Looks like just renaming the GitHub repo should be fine. No code changes required.
