### ISSUE TITLE
Raven installed but server/raven Not Found 

### ISSUE THREAD

**Issue by webcomx** [The-Commit-Company/raven#1067]
![image](https://github.com/user-attachments/assets/dc4d06f9-2267-4df1-91f7-b0ee51eed8bd)

l used the below , any pointers ? 
bench get-app https://github.com/The-Commit-Company/Raven.git
bench --site yoursite.name install-app raven

**Comment by webcomx** [comment]
bench get-app https://github.com/The-Commit-Company/Raven.git
bench --site yoursite.name install-app raven

**Comment by nikkothari22** [comment]
Can you run `bench build --app raven`?

**Comment by webcomx** [comment]
> Can you run `bench build --app raven`?
This the error l get below..

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/erpnext/frappe-bench/apps/frappe/frappe/commands/utils.py", line 77, in build
    bundle(
  File "/erpnext/frappe-bench/apps/frappe/frappe/build.py", line 254, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)  File "/erpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps raven --run-build-command' returned non-zero exit status 1.

**Comment by nikkothari22** [comment]
Hey, 

Can you try the following:

`bench get-app https://github.com/The-Commit-Company/raven.git`

`bench --site mysite.com install-app raven`

Replace `mysite.com` with the name of your site you want to install Raven on.
