### ISSUE TITLE
frappe.exceptions.LinkValidationError: Could not find User: Administrator

### ISSUE THREAD

**Issue by vivek-4444** [The-Commit-Company/raven#1106]
(env) frappe@bafec862d4b7:/workspace/development/frappe-bench$ bench --site raven.localhost install-app raven

Installing raven...
Updating DocTypes for raven         : [========================================] 100%
Setting up Raven...
Document Insert Error
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/raven/raven/raven_channel_management/doctype/raven_channel/raven_channel.py", line 102, in after_insert
    ).insert()
      ^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 930, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find User: Administrator

Thank you for installing Raven!
Updating Dashboard for raven

**Comment by shubham9511s** [comment]
do one think go to user and give the role of administrator raven user.

**Comment by nikkothari22** [comment]
@vivek-4444 What @shubham9511s is suggesting will work, but I have noticed this issue on new sites created on Frappe Cloud as well. I think when installing, we should not add any members to the "general" channel since it's an open channel to begin with. That's what causes this issue.

**Comment by vivek-4444** [comment]
![CGe7gvrfGTkl](https://github.com/user-attachments/assets/e37ca9a3-5d90-4cfd-9f98-508480ee64c0)

**Comment by vivek-4444** [comment]
i reinstall raven but i got this error :

(env) frappe@bafec862d4b7:/workspace/development/frappe-bench$ bench --site raven.localhost install-app raven 

Installing raven...
Updating DocTypes for raven         : [========================================] 100%
Setting up Raven...
Current user:  Administrator
Document Insert Error
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 308, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/raven/raven/raven_channel_management/doctype/raven_channel/raven_channel.py", line 104, in after_insert
    ).insert()
      ^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 283, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 930, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find User: Administrator

Thank you for installing Raven!
Updating Dashboard for raven

**Comment by nikkothari22** [comment]
@vivek-4444 - did you go to "Raven User" and check if a raven user is created for "Administrator"?

**Comment by vivek-4444** [comment]
solved 😊 
--  i manually add record

new_raven_user = frappe.get_doc({
	"doctype": "Raven User",
	"user": "Administrator"
})
new_raven_user.insert()
frappe.db.commit()  

Thanks for support @nikkothari22 @shubham9511s
