### ISSUE TITLE
App notification_relay is not installed - Raven

### ISSUE THREAD

**Issue by vivek-4444** [The-Commit-Company/raven#1111]
Server Error :

Traceback (most recent call last):
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    method = get_attr(cmd)
             ^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 289, in get_attr
    method = frappe.get_attr(cmd)
             ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1761, in get_attr
    throw(_("App {0} is not installed").format(app_name), AppNotInstalledError)
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.AppNotInstalledError: App notification_relay is not installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 78, in execute_cmd
    frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Failed to get method for command notification_relay.api.get_config with App notification_relay is not installed

error show in bench start console

**Comment by nikkothari22** [comment]
Notification relay is a feature on Frappe Cloud, so it won't run locally.

**Comment by vivek-4444** [comment]
> Notification relay is a feature on Frappe Cloud, so it won't run locally.

i setup my site in cloud

**Comment by nikkothari22** [comment]
Can you join the community here and send me a message: https://community.ravenapp.cloud/ ? I'll have a look.

**Comment by vivek-4444** [comment]
Okay i join community

**Comment by nikkothari22** [comment]
@vivek-4444 Push notifications are only supported on Frappe Cloud, not available for self hosting (yet).
