### ISSUE TITLE
Missing Message Action and Schedule Message Options

### ISSUE THREAD

**Issue by Venkateshvenki404224** [The-Commit-Company/raven#1113]
![image](https://github.com/user-attachments/assets/849c9fab-d994-4e62-b69e-ecff025a970b)

I am currently unable to see certain options like "Message Action" and "Schedule Message" in the settings panel under the "Frappe HR" integration. I have confirmed that the settings are configured correctly, but these options are not appearing. Other users seem to be facing a similar issue.

**Comment by nikkothari22** [comment]
Hey @Venkateshvenki404224 - I think the build command didn't run on your machine. 

I'm assuming you have a self hosted setup - can you run the command: bench build --app raven? 

If it's on Frappe Cloud and on a public bench, it'll take some time for the latest updates to show up since they update the public bench every week.

**Comment by Venkateshvenki404224** [comment]
```
labs@frappe:~/portal-bench$ bench build --app raven
✔ Application Assets Linked                                                                                                                                                                                              


yarn run v1.22.22
$ node esbuild --production --apps raven --run-build-command
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
File                                                        Size

raven/dist/js/
└─ raven.bundle.OIRS4GEZ.js                                 9.30 Kb

raven/dist/
└─ raven_chat.bundle.J2F7CDET.js                            510.72 Kb

raven/dist/css/
└─ raven.bundle.MHJ4RVR7.css                                6.88 Kb

raven/dist/css-rtl/
└─ raven.bundle.TSEHUGYE.css                                6.89 Kb

 DONE  Total Build Time: 1.661s


Running build command for raven
$ cd frontend && yarn build
$ vite build --base=/assets/raven/raven/ && yarn copy-html-entry
vite v4.5.5 building for production...
✓ 228 modules transformed.
[vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "react-error-boundary" from "/home/labs/portal-bench/apps/raven/frontend/src/components/feature/settings/ai/functions/VariableBuilder.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "react-error-boundary" from "/home/labs/portal-bench/apps/raven/frontend/src/components/feature/settings/ai/functions/VariableBuilder.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/labs/portal-bench/apps/raven/node_modules/vite/dist/node/chunks/dep-b2890f90.js:48216:27)
    at Object.onwarn (file:///home/labs/portal-bench/apps/raven/frontend/vite.config.ts.timestamp-1729185297984-1b682859a6ab1.mjs:112:13)
    at onwarn (file:///home/labs/portal-bench/apps/raven/node_modules/@vitejs/plugin-react/dist/index.mjs:264:40)
    at onRollupWarning (file:///home/labs/portal-bench/apps/raven/node_modules/vite/dist/node/chunks/dep-b2890f90.js:48245:9)
    at onwarn (file:///home/labs/portal-bench/apps/raven/node_modules/vite/dist/node/chunks/dep-b2890f90.js:47976:13)
    at file:///home/labs/portal-bench/apps/raven/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///home/labs/portal-bench/apps/raven/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/labs/portal-bench/apps/raven/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///home/labs/portal-bench/apps/raven/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/home/labs/portal-bench/apps/frappe/esbuild/esbuild.js:519:3)
    at execute (/home/labs/portal-bench/apps/frappe/esbuild/esbuild.js:137:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1977470,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/labs/portal-bench/apps/frappe/frappe/utils/bench_helper.py", line 128, in <module>
    main()
  File "/home/labs/portal-bench/apps/frappe/frappe/utils/bench_helper.py", line 34, in main
    FrappeCommandGroup(commands=commands)(prog_name="bench")
  File "/home/labs/portal-bench/env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labs/portal-bench/env/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/labs/portal-bench/env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labs/portal-bench/env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labs/portal-bench/env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labs/portal-bench/env/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labs/portal-bench/apps/frappe/frappe/commands/utils.py", line 87, in build
    bundle(
  File "/home/labs/portal-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/labs/portal-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps raven --run-build-command' returned non-zero exit status 1.
labs@frappe:~/portal-bench$ 
```


I m getting the above error

**Comment by Venkateshvenki404224** [comment]
@nikkothari22 
I have uninstalled and reinstalled the app . 
Now it worked .
Thank you
