### ISSUE TITLE
Installation - ReferenceError: require is not defined

### ISSUE THREAD

**Issue by keithkhl** [The-Commit-Company/raven#1129]
I got below error during Raven app installation.
I am running Frappe/ERPNext on a hard machine (not on docker).

I can see that 'require' is used for dark theme's plugin.
Not sure why the node.js function does not run, but it happens to other Frappe/ERPNext apps.

My environment is

- Node.js : v23.0.0 - npm and vm are also latest
- Python : 3.10 (and venv)
- Frappe / ERPNext - verstion 15

-------
ReferenceError: require is not defined
    at file:///var/www/frappe/apps/raven/frontend/tailwind.config.js:193:12
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:367:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:325:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1392:24)
    at Module._compile (node:internal/modules/cjs/loader:1525:5)
    at Object..js (node:internal/modules/cjs/loader:1680:16)
    at Module.load (node:internal/modules/cjs/loader:1328:32)
    at Function._load (node:internal/modules/cjs/loader:1138:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)

Node.js v23.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:882:11)
    at execSync (node:child_process:954:15)
    at run_build_command_for_apps (/var/www/frappe/apps/frappe/esbuild/esbuild.js:448:5)
    at execute (/var/www/frappe/apps/frappe/esbuild/esbuild.js:125:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 127951,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.

**Comment by nikkothari22** [comment]
Use Node v18 or 20. This is probably an issue with Node v23.

**Comment by keithkhl** [comment]
I've also tried with v16.10.4, 18.20.2, 18.20.4, and 20.9.0 (LTS)
All failed.

**Comment by nikkothari22** [comment]
Oh okay. Let me have a look

**Comment by nikkothari22** [comment]
@keithkhl I have pushed an update in the develop branch which switches the "require" to an "import". Should work now.
