### ISSUE TITLE
ERPNext instance breaks after installing Raven

### ISSUE THREAD

**Issue by hesham1216** [The-Commit-Company/raven#1165]
Hello Guys,

I have installed a fresh ERPNext 15 locally on newly installed Ubuntu 24 version on a local machine, and also the same setup on a virtual machine.

Both works great (I tried installing Frappe CRM as well) it was success.

I tried to install Raven using the documented commands:

> bench get-app https://github.com/The-Commit-Company/raven.git

> bench --site <yoursite.name> install-app raven

But this is what happens:

![image](https://github.com/user-attachments/assets/23371864-8948-4183-9af0-a73165d6eb9b)

And it shows this Error on the landing page:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 30, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 166, in get
    frappe.get_attr(hook)(bootinfo=bootinfo)
  File "apps/raven/raven/boot.py", line 6, in boot_session
    bootinfo.show_raven_chat_on_desk = frappe.db.get_single_value(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 839, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1317, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/meta.py", line 63, in get_meta
    meta = Meta(doctype)
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: DocType Raven Settings not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 530, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/www/app.py", line 32, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed
```

This error code in the trminal:

```
`erp@erp:~/frappe-bench$ sudo bench --site erp.sait.com.sa install-app raven

Installing raven...
Setting up Raven...
Installation for Raven failed due to an error. Please try re-installing the app or report the issue on https://github.com/The-Commit-Company/Raven/issues/new if not resolved.
An error occurred while installing raven: Module import failed for Raven User, the DocType you're trying to open might be deleted.
Error: No module named 'frappe.core.doctype.raven_user'
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 478, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['erp.sait.com.sa'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('raven',)
      force = False
      _install_app = <function install_app at 0x750e2b926020>
      filelock = <function filelock at 0x750e2b90fe20>
      exit_code = 0
      site = 'erp.sait.com.sa'
      app = 'raven'
      err = ImportError("Module import failed for Raven User, the DocType you're trying to open might be deleted.\nError: No module named 'frappe.core.doctype.raven_user'")
  File "apps/frappe/frappe/installer.py", line 326, in install_app
    frappe.get_attr(after_install)()
      name = 'raven'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x750e2ac11f80>
      sync_for = <function sync_for at 0x750e2ac12d40>
      sync_customizations = <function sync_customizations at 0x750e2c5547c0>
      sync_fixtures = <function sync_fixtures at 0x750e2ac13060>
      app_hooks = {'add_to_apps_screen': [{'name': 'raven', 'logo': '/assets/raven/raven-logo.png', 'title': 'Raven', 'route': '/raven', 'has_permission': 'raven.permissions.check_app_permission'}], 'additional_timeline_content': {'*': ['raven.api.raven_message.get_timeline_message_content']}, 'after_install': ['raven.install.after_install'], 'after_uninstall': ['raven.uninstall.after_uninstall'], 'app_description': ['Messaging Application'], 'app_email': ['support@thecommit.company'], 'app_include_css': ['raven.bundle.css'], 'app_include_js': ['raven.bundle.js'], 'app_license': ['AGPLv3'], 'app_logo': ['/assets/raven/raven-logo.png'], 'app_logo_url': ['/assets/raven/raven-logo.png'], 'app_name': ['raven'], 'app_publisher': ['The Commit Company (Algocode Technologies Pvt. Ltd.)'], 'app_title': ['Raven'], 'app_version': ['2.0.0'], 'doc_events': {'User': {'after_insert': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven'], 'on_update': ['raven.raven.doctype.raven_user.raven_user.add_user_to_ra...
      installed_apps = ['frappe', 'erpnext', 'hrms']
      after_install = 'raven.install.after_install'
  File "apps/raven/raven/install.py", line 23, in after_install
    raise e
      BUG_REPORT_URL = 'https://github.com/The-Commit-Company/Raven/issues/new'
  File "apps/raven/raven/install.py", line 10, in after_install
    create_raven_user_for_administrator()
      BUG_REPORT_URL = 'https://github.com/The-Commit-Company/Raven/issues/new'
  File "apps/raven/raven/install.py", line 29, in create_raven_user_for_administrator
    frappe.get_doc(
  File "apps/frappe/frappe/__init__.py", line 1290, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
      args = ({'doctype': 'Raven User', 'user': 'Administrator', 'full_name': 'Administrator', 'type': 'User'},)
      kwargs = {}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
      args = ({'doctype': 'Raven User', 'user': 'Administrator', 'full_name': 'Administrator', 'type': 'User'},)
      kwargs = {'doctype': 'Raven User', 'user': 'Administrator', 'full_name': 'Administrator', 'type': 'User'}
      doctype = 'Raven User'
  File "apps/frappe/frappe/model/base_document.py", line 70, in get_controller
    site_controllers[doctype] = import_controller(doctype)
      doctype = 'Raven User'
      site_controllers = {'Module Def': <class 'frappe.core.doctype.module_def.module_def.ModuleDef'>, 'DocField': <class 'frappe.core.doctype.docfield.docfield.DocField'>, 'DocPerm': <class 'frappe.core.doctype.docperm.docperm.DocPerm'>, 'DocType Link': <class 'frappe.core.doctype.doctype_link.doctype_link.DocTypeLink'>, 'System Settings': <class 'frappe.core.doctype.system_settings.system_settings.SystemSettings'>, 'Notification Settings': <class 'frappe.desk.doctype.notification_settings.notification_settings.NotificationSettings'>, 'DefaultValue': <class 'frappe.core.doctype.defaultvalue.defaultvalue.DefaultValue'>, 'Payment Reconciliation': <class 'erpnext.accounts.doctype.payment_reconciliation.payment_reconciliation.PaymentReconciliation'>, 'Customize Form': <class 'frappe.custom.doctype.customize_form.customize_form.CustomizeForm'>, 'DocType Action': <class 'frappe.core.doctype.doctype_action.doctype_action.DocTypeAction'>, 'DocType State': <class 'frappe.core.doctype.doctype_state.doctype_state.DocTyp...
  File "apps/frappe/frappe/model/base_document.py", line 95, in import_controller
    module = load_doctype_module(doctype, module_name)
      doctype = 'Raven User'
      Document = <class 'frappe.model.document.Document'>
      NestedSet = <class 'frappe.utils.nestedset.NestedSet'>
      module_name = 'Core'
      doctype_info = None
      module_path = None
      class_overrides = {'Address': ['erpnext.accounts.custom.address.ERPNextAddress'], 'Employee': ['hrms.overrides.employee_master.EmployeeMaster'], 'Timesheet': ['hrms.overrides.employee_timesheet.EmployeeTimesheet'], 'Payment Entry': ['hrms.overrides.employee_payment_entry.EmployeePaymentEntry'], 'Project': ['hrms.overrides.employee_project.EmployeeProject']}
  File "apps/frappe/frappe/modules/utils.py", line 258, in load_doctype_module
    raise ImportError(msg) from e
      doctype = 'Raven User'
      module = 'Core'
      prefix = ''
      suffix = ''
      app = 'frappe'
      key = ********
      module_name = 'frappe.core.doctype.raven_user.raven_user'
      msg = "Module import failed for Raven User, the DocType you're trying to open might be deleted.\nError: No module named 'frappe.core.doctype.raven_user'"
builtins.ImportError: Module import failed for Raven User, the DocType you're trying to open might be deleted.
Error: No module named 'frappe.core.doctype.raven_user'
erp@erp:~/frappe-bench$ sudo bench --site erp.sait.com.sa install-app raven
App raven already installed
erp@erp:~/frappe-bench$
`
```

Thank you for your support very much :)

By the way, the system get back to normal condition with no errors when I remove thr Raven app through:

> bench uninstall-app raven

![image](https://github.com/user-attachments/assets/52993006-325e-4cf6-9675-0c5e08452296)

**Comment by nikkothari22** [comment]
@hesham1216 It looks like this might be related to the install script. On install, Raven adds all roles to the Administrator - and hence it tries to create a "Raven User" doctype for it on install. Surprisingly, this error does not come up when we install it on Frappe Cloud :/

We'll investigate and get back o you. For now, you can simply uninstall and then install the app again and it should work.

**Comment by hesham1216** [comment]
> @hesham1216 It looks like this might be related to the install script. On install, Raven adds all roles to the Administrator - and hence it tries to create a "Raven User" doctype for it on install. Surprisingly, this error does not come up when we install it on Frappe Cloud :/
> 
> We'll investigate and get back to you. For now, you can simply uninstall and then install the app again and it should work.

Thank you for your reply

Just wanted to let know, it seems the problem was with the npm (to be honest I am not sure :D) (maybe just re-installing the Raven app).

I used the below commands:

> sudo npm cache clean -f
sudo npm install -g n
sudo n stable

Then I tried to install Raven again and it worked 😍

Thank you for your support 🙏
