### ISSUE TITLE
Frappe cloud Installation Failed

### ISSUE THREAD

**Issue by sammish** [The-Commit-Company/Raven#477]
Hello Team,

![image](https://github.com/The-Commit-Company/Raven/assets/12432802/8f71f09c-8c23-4fc2-ae2c-ea2fc352b700)

bench get-app raven
Getting Raven
$ git clone file:///home/frappe/context/apps/raven  --depth 1 --origin upstream
Cloning into 'raven'...
Ignoring dependencies of file:///home/frappe/context/apps/raven. To install dependencies use --resolve-deps
Installing raven
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/raven
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ yarn install-web && yarn install-mobile
yarn run v1.22.19
$ cd raven-app && yarn install
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @chakra-ui/icons@2.0.19" has unmet peer dependency "@chakra-ui/system@>=2.0.0".
warning "@chakra-ui/icons > @chakra-ui/icon@3.0.16" has unmet peer dependency "@chakra-ui/system@>=2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/form-control@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/icon@^3.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/layout@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/media-query@^3.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/menu@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/spinner@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/system@^2.0.0".
warning "frappe-react-sdk > frappe-js-sdk@1.3.6" has unmet peer dependency "axios@^0.26.1".
warning " > quill-linkify@0.3.0" has unmet peer dependency "quill@^1.3.7".
warning " > quill-linkify@0.3.0" has unmet peer dependency "quill-delta@^3.6.2 || ^4.2.2".
[4/4] Building fresh packages...
Done in 6.98s.
yarn run v1.22.19
$ cd mobile && yarn install
[1/4] Resolving packages...
[2/4] Fetching packages...
error @stencil/core@4.1.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR:
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 581, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
INFO: A newer version of bench is available: 5.15.2 → 5.17.2
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/raven `#stage-apps-raven`]: exit code: 1
> [stage-0 32/34] RUN --mount=type=cache,target=/home/frappe/.cache,uid=1000,gid=1000 --mount=type=bind,source=apps/raven,target=/home/frappe/context/apps/raven bench get-app file:///home/frappe/context/apps/raven `#stage-apps-raven`:
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/raven `#stage-apps-raven`]: exit code: 1

**Comment by nikkothari22** [comment]
Hey @sammish - your Node version should be equal to or greater than v16.

You can ask Frappe Cloud support to make this change for you or you can change it yourself in your site/bench settings.

**Comment by sammish** [comment]
@nikkothari22 Noted
