### ISSUE TITLE
Error creating frappe user

### ISSUE THREAD

**Issue by git-avc** [The-Commit-Company/Raven#596]
After installing Raven 1.3.0 , user creation in Frappe fails. 
Disabling before_validate in hooks.py or disabling Raven user autocreation on settings, works fine.

Error: 
Could not find User: user@domain.com

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1704, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 227, in save
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 356, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1077, in run_before_save_methods
    self.run_method("before_validate")
  File "apps/frappe/frappe/model/document.py", line 952, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1318, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1302, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/raven/raven/raven/doctype/raven_user/raven_user.py", line 103, in add_user_to_raven
    raven_user.insert()
  File "apps/frappe/frappe/model/document.py", line 278, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 920, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 592, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 564, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 515, in _raise_exception
    raise exc
frappe.exceptions.LinkValidationError: Could not find User: user@domain.com`

**Comment by nikkothari22** [comment]
Hey @git-avc , thanks for reporting this. I have pushed a fix - if you tried it on your local environment, can you check if it's running well? I have tested it, and pushed the changes to Frappe Cloud, but that will take time to deploy.

**Comment by git-avc** [comment]
Hi @nikkothari22!
Seems it's working fine now 👍
