### ISSUE TITLE
Unable to install Raven in local server.

### ISSUE THREAD

**Issue by atulraj85** [The-Commit-Company/Raven#861]
Steps I did:

1. Initialized a new bench
2. Update frappe app to latest
```
{
    "frappe": {
        "resolution": {
            "commit_hash": null,
            "branch": null
        },
        "required": [],
        "idx": 1,
        "version": "16.0.0-dev"
    },
    "raven": {
        "is_repo": true,
        "resolution": {
            "commit_hash": "d95748fd0134289ddea51f7bca94af8313d1e376",
            "branch": "develop"
        },
        "required": [],
        "idx": 2,
        "version": "1.5.1"
    }
}
```

3. Installed  Raven 
4. Got this Error in terminal 

```
Installing raven...
An error occurred while installing raven: Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 496, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['atulya.local'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('raven',)
      force = False
      _install_app = <function install_app at 0x7f0c00cbe020>
      filelock = <function filelock at 0x7f0c00cb37e0>
      exit_code = 0
      site = 'atulya.local'
      app = 'raven'
      err = ImportError("Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'")
  File "apps/frappe/frappe/installer.py", line 324, in install_app
    frappe.get_attr(after_install)()
      name = 'raven'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f0c000ac680>
      sync_for = <function sync_for at 0x7f0c000ad440>
      sync_customizations = <function sync_customizations at 0x7f0c00e5bce0>
      sync_fixtures = <function sync_fixtures at 0x7f0c000ad6c0>
      app_hooks = {'additional_timeline_content': {'*': ['raven.api.raven_message.get_timeline_message_content']}, 'after_install': ['raven.install.after_install'], 'after_uninstall': ['raven.uninstall.after_uninstall'], 'app_description': ['Messaging Application'], 'app_email': ['support@thecommit.company'], 'app_include_css': ['raven.bundle.css'], 'app_include_js': ['raven.bundle.js'], 'app_license': ['AGPLv3'], 'app_name': ['raven'], 'app_publisher': ['The Commit Company'], 'app_title': ['Raven'], 'app_version': ['1.5.1'], 'doc_events': {'User': {'after_insert': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven'], 'on_update': ['raven.raven.doctype.raven_user.raven_user.add_user_to_raven'], 'on_trash': ['raven.raven.doctype.raven_user.raven_user.remove_user_from_raven']}}, 'export_python_type_annotations': [True], 'extend_bootinfo': ['raven.boot.boot_session'], 'has_permission': {'Raven Channel': ['raven.permissions.channel_has_permission'], 'Raven Channel Member': ['raven.permissions.cha...
      installed_apps = ['frappe']
      after_install = 'raven.install.after_install'
  File "apps/raven/raven/install.py", line 6, in after_install
    create_general_channel()
  File "apps/raven/raven/install.py", line 11, in create_general_channel
    channel = frappe.new_doc("Raven Channel")
  File "apps/frappe/frappe/__init__.py", line 1227, in new_doc
    new_doc = get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
      doctype = 'Raven Channel'
      parent_doc = None
      parentfield = None
      as_dict = False
      kwargs = {}
      get_new_doc = <function get_new_doc at 0x7f0bfe196f20>
  File "apps/frappe/frappe/model/create_new.py", line 22, in get_new_doc
    frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
      doctype = 'Raven Channel'
      parent_doc = None
      parentfield = None
      as_dict = False
  File "apps/frappe/frappe/model/create_new.py", line 35, in make_new_doc
    doc = frappe.get_doc({"doctype": doctype, "__islocal": 1, "owner": frappe.session.user, "docstatus": 0})
      doctype = 'Raven Channel'
  File "apps/frappe/frappe/__init__.py", line 1371, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
      args = ({'doctype': 'Raven Channel', '__islocal': 1, 'owner': 'Administrator', 'docstatus': 0},)
      kwargs = {}
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    controller = get_controller(doctype)
      args = ({'doctype': 'Raven Channel', '__islocal': 1, 'owner': 'Administrator', 'docstatus': 0},)
      kwargs = {'doctype': 'Raven Channel', '__islocal': 1, 'owner': 'Administrator', 'docstatus': 0}
      doctype = 'Raven Channel'
  File "apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
      doctype = 'Raven Channel'
      site_controllers = {'Module Def': <class 'frappe.core.doctype.module_def.module_def.ModuleDef'>, 'DocField': <class 'frappe.core.doctype.docfield.docfield.DocField'>, 'DocPerm': <class 'frappe.core.doctype.docperm.docperm.DocPerm'>, 'DocType Link': <class 'frappe.core.doctype.doctype_link.doctype_link.DocTypeLink'>, 'System Settings': <class 'frappe.core.doctype.system_settings.system_settings.SystemSettings'>, 'Notification Settings': <class 'frappe.desk.doctype.notification_settings.notification_settings.NotificationSettings'>, 'DefaultValue': <class 'frappe.core.doctype.defaultvalue.defaultvalue.DefaultValue'>, 'Customize Form': <class 'frappe.custom.doctype.customize_form.customize_form.CustomizeForm'>, 'DocType Action': <class 'frappe.core.doctype.doctype_action.doctype_action.DocTypeAction'>, 'DocType State': <class 'frappe.core.doctype.doctype_state.doctype_state.DocTypeState'>, 'Customize Form Field': <class 'frappe.custom.doctype.customize_form_field.customize_form_field.CustomizeFormField'>, 'P...
  File "apps/frappe/frappe/model/base_document.py", line 96, in import_controller
    module = load_doctype_module(doctype, module_name)
      doctype = 'Raven Channel'
      Document = <class 'frappe.model.document.Document'>
      NestedSet = <class 'frappe.utils.nestedset.NestedSet'>
      module_name = 'Core'
      doctype_info = None
      module_path = None
      class_overrides = []
  File "apps/frappe/frappe/modules/utils.py", line 253, in load_doctype_module
    raise ImportError(msg) from e
      doctype = 'Raven Channel'
      module = 'Core'
      prefix = ''
      suffix = ''
      app = 'frappe'
      key = ********
      module_name = 'frappe.core.doctype.raven_channel.raven_channel'
      msg = "Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'"
builtins.ImportError: Module import failed for Raven Channel, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.raven_channel'

```

5. Visited site:port/raven

This error pops up

```
Traceback (most recent call last):
  File "apps/raven/raven/www/raven.py", line 24, in get_context
    boot = frappe.sessions.get()
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/sessions.py", line 162, in get
    frappe.get_attr(hook)(bootinfo=bootinfo)
  File "apps/raven/raven/boot.py", line 6, in boot_session
    bootinfo.show_raven_chat_on_desk = frappe.db.get_single_value(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 849, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1398, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/meta.py", line 64, in get_meta
    meta = Meta(doctype)
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/meta.py", line 118, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 128, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 124, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 174, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 683, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 648, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 599, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: DocType Raven Settings not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 521, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/raven/raven/www/raven.py", line 26, in get_context
    raise frappe.SessionBootFailed from e
frappe.exceptions.SessionBootFailed

```

![image](https://github.com/The-Commit-Company/Raven/assets/121156542/7014b892-f227-4f7d-bc97-eb107cb7a9d1)

About my desk.

How do I run it?

**Comment by nikkothari22** [comment]
Do you have multiple sites on your bench?

**Comment by atulraj85** [comment]
No @nikkothari22, I created a new bench just for Raven only.

**Comment by nikkothari22** [comment]
I am not able to reproduce the issue. 

Can you get the latest version of Raven (I just updated the develop branch with fixtures) and try again?

**Comment by atulraj85** [comment]
Sure will try again!
