### ISSUE TITLE
After updating to v1.5.5 (develop) I get This error

### ISSUE THREAD

**Issue by yahyaoudra** [The-Commit-Company/Raven#908]
![Screenshot 2024-05-06 at 18 03 35](https://github.com/The-Commit-Company/Raven/assets/67019341/6016aba2-73e7-4d01-a228-708cc9ff0275)

**Comment by yahyaoudra** [comment]
Installed Apps
ERPNext: v15.22.2 (version-15)

Frappe Framework: v15.25.0 (version-15)

Helpdesk: v0.10.0 (main)

Frappe HR: v16.0.0-dev (develop)

Frappe LMS: v1.0.0 (main)

Raven: v1.5.5 (develop)

**Comment by nikkothari22** [comment]
I think your React app isn't built correctly. Run `bench build` and if the error persists, share the logs.

**Comment by yahyaoudra** [comment]
@nikkothari22 still same problem

**Comment by nikkothari22** [comment]
@yahyaoudra Can you share the logs of the bench build process?

**Comment by nikkothari22** [comment]
This API has been moved in v1.5+ and hence the React app that you have running is calling an old API - so the React app is definitely not updated.

**Comment by yahyaoudra** [comment]
Here's the logs
```shell
Assets for Release v15.25.0 don't exist
✔ Application Assets Linked                                                                                      


yarn run v1.22.21
warning ../../../package.json: No license field
$ node esbuild --production --run-build-command
File                                                        Size

frappe/dist/js/
├─ bootstrap-4-web.bundle.FOZOVELL.js                       1.73 Kb
├─ controls.bundle.QQ46RCFJ.js                              1234.38 Kb
├─ data_import_tools.bundle.GNL3BWOK.js                     126.56 Kb
├─ desk.bundle.WRQEDU4O.js                                  1344.20 Kb
├─ dialog.bundle.4B4VFQRT.js                                57.02 Kb
├─ form.bundle.II35OJ2Q.js                                  167.35 Kb
├─ frappe-web.bundle.BOX5EJW7.js                            829.30 Kb
├─ libs.bundle.TIV7ZGVY.js                                  556.25 Kb
├─ list.bundle.7HNZQYOT.js                                  195.62 Kb
├─ logtypes.bundle.EKN7LWKW.js                              0.73 Kb
├─ onboarding_tours.bundle.RAUR6X4Z.js                      7.60 Kb
├─ report.bundle.7EDXELBQ.js                                197.39 Kb
├─ sentry.bundle.IPS6PK2M.js                                69.50 Kb
├─ telemetry.bundle.LKEZCADB.js                             2.59 Kb
├─ user_profile_controller.bundle.ZJ6AYZ5P.js               11.96 Kb
├─ video_player.bundle.DUYYLSFO.js                          120.67 Kb
├─ web_form.bundle.CSZ7J2CG.js                              1425.93 Kb
├─ form_builder.bundle.PYSFZX3S.js                          796.56 Kb
├─ form_builder.bundle.AS6W75M2.css                         23.02 Kb
├─ print_format_builder.bundle.3YCNST3U.js                  685.24 Kb
├─ print_format_builder.bundle.FFVPBPB6.css                 5.54 Kb
├─ workflow_builder.bundle.LXRUMVA2.js                      351.50 Kb
├─ workflow_builder.bundle.NCYHBU52.css                     11.02 Kb
├─ build_events.bundle.BCX32TWL.js                          105.71 Kb
├─ build_events.bundle.CZHNP7YC.css                         1.29 Kb
├─ file_uploader.bundle.5SUMRMUP.js                         201.83 Kb
├─ file_uploader.bundle.WV4MAVCJ.css                        6.53 Kb
└─ kanban_board.bundle.IQTBPBLP.js                          578.17 Kb

lms/dist/js/
└─ website.bundle.C6TCYSIP.js                               86.83 Kb

helpdesk/dist/js/
└─ helpdesk.bundle.77U63EU3.js                              1.88 Kb

raven/dist/js/
└─ raven.bundle.YKUWCOAX.js                                 9.30 Kb

raven/dist/
└─ raven_chat.bundle.MXS2S6TW.js                            499.37 Kb

erpnext/dist/js/
├─ bank-reconciliation-tool.bundle.ALGDCWUD.js              17.17 Kb
├─ erpnext-web.bundle.J4A2DQB4.js                           0.29 Kb
├─ erpnext.bundle.FGLT6TCC.js                               216.00 Kb
├─ item-dashboard.bundle.DFIPMDTM.js                        10.24 Kb
├─ point-of-sale.bundle.SDQCB6WE.js                         92.61 Kb
└─ bom_configurator.bundle.D2UVDA3I.js                      8.63 Kb

hrms/dist/js/
├─ hierarchy-chart.bundle.5NWJGABT.js                       225.55 Kb
├─ hrms.bundle.NPAUDBQ5.js                                  10.55 Kb
├─ interview.bundle.C7CDEMYA.js                             1.66 Kb
└─ performance.bundle.63UL5NS7.js                           3.70 Kb

frappe/dist/css/
├─ desk.bundle.KG7WWLW3.css                                 591.00 Kb
├─ email.bundle.WXTIUCHS.css                                5.97 Kb
├─ login.bundle.YPZLHM2S.css                                32.31 Kb
├─ print.bundle.3NRF4O3O.css                                203.35 Kb
├─ print_format.bundle.CD35H273.css                         186.14 Kb
├─ report.bundle.CNKAFZZ2.css                               5.33 Kb
├─ web_form.bundle.CM4ZYXAN.css                             14.69 Kb
└─ website.bundle.BPNMZUSO.css                              443.56 Kb

lms/dist/css/
└─ lms.bundle.UBIVHHH5.css                                  32.40 Kb

raven/dist/css/
└─ raven.bundle.XPU6LLRP.css                                6.88 Kb

erpnext/dist/css/
├─ erpnext-web.bundle.2NJPHRB6.css                          2.86 Kb
├─ erpnext.bundle.7QV7OQFF.css                              44.14 Kb
└─ erpnext_email.bundle.LHVBQTND.css                        0.56 Kb

hrms/dist/css/
└─ hrms.bundle.IKCTEPTD.css                                 6.06 Kb

frappe/dist/css-rtl/
├─ desk.bundle.WK6URMEU.css                                 591.51 Kb
├─ email.bundle.WKZ4ABVL.css                                5.98 Kb
├─ login.bundle.YP5JH4RJ.css                                32.31 Kb
├─ print.bundle.UVQK4HNY.css                                203.51 Kb
├─ print_format.bundle.TI7BANPL.css                         186.26 Kb
├─ report.bundle.VVBXIRNE.css                               5.33 Kb
├─ web_form.bundle.VLVR5DGP.css                             14.68 Kb
└─ website.bundle.6CHJT4V7.css                              443.72 Kb

lms/dist/css-rtl/
└─ lms.bundle.VF4TC2RL.css                                  32.42 Kb

raven/dist/css-rtl/
└─ raven.bundle.X2F4MR44.css                                6.89 Kb

erpnext/dist/css-rtl/
├─ erpnext-web.bundle.TWQLZ3AQ.css                          2.87 Kb
├─ erpnext.bundle.2YGS7YTU.css                              44.13 Kb
└─ erpnext_email.bundle.KSOIDCAS.css                        0.56 Kb

hrms/dist/css-rtl/
└─ hrms.bundle.SNOJKFUY.css                                 6.07 Kb

 DONE  Total Build Time: 29.058s


Running build command for helpdesk
warning ../../../package.json: No license field
$ cd desk && yarn build
warning ../../../../package.json: No license field
$ vite build --base=/assets/helpdesk/desk/ && yarn copy-html-entry
[unplugin-vue-components] component "Autocomplete"(/home/frappe/frappe-bench/apps/helpdesk/desk/src/components/global/Autocomplete.vue) has naming conflicts with other components, ignored.
(node:2277901) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
vite v4.1.4 building for production...
transforming (161) ~icons/espresso/alert-circleBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
transforming (252) node_modules/@tiptap/extension-link/dist/index.js
Inter-DisplayRegular.woff2?v=3.19 referenced in /home/frappe/frappe-bench/apps/helpdesk/desk/src/index.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
transforming (1558) node_modules/util-deprecate/browser.jsUse of eval in "src/pages/ticket/TicketActionsTags.vue?vue&type=script&setup=true&lang.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 1676 modules transformed.
rendering chunks (2)...Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at genericNodeError (node:internal/errors:956:15)
    at wrappedFn (node:internal/errors:510:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:451:5)
    at execute (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:128:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 137,
  signal: null,
  output: [ null, null, null ],
  pid: 2277868,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 77, in build
    bundle(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 254, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --run-build-command' returned non-zero exit status 1.
```

**Comment by yahyaoudra** [comment]
My react server version is 18.3.1

**Comment by nikkothari22** [comment]
@yahyaoudra Looks like the issue is with the helpdesk app not being built correctly. Since the process fails there, it does not build Raven. Can you pull the latest update of both helpdesk and Raven and try again?

Also, to just build raven, you can use `bench build --app raven`
