### ISSUE TITLE
Getting Unexpected Application Error!

### ISSUE THREAD

**Issue by midhat2020** [The-Commit-Company/Raven#979]
On click of select contact button we are getting the following error.
![WhatsApp Image 2024-07-25 at 10 00 22](https://github.com/user-attachments/assets/7b3c01ac-c510-4a81-b2c4-9abf2b3a0592)

![WhatsApp Image 2024-07-25 at 09 57 24](https://github.com/user-attachments/assets/9418d7e9-3e49-4081-95ab-bb85e78301cd)
`Unexpected Application Error!
Cannot use 'in' operator to search for 'current' in null
TypeError: Cannot use 'in' operator to search for 'current' in null
    at https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:136:13825
    at https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:136:13907
    at kf (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:24300)
    at T2 (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:31643)
    at NE (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:31499)
    at Q7 (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:31049)
    at r9 (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:40940)
    at Ta (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:40298)
    at P2 (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:40:36908)
    at ma (https://www.sitename.info/assets/raven/raven/assets/index-478ce558.js:38:3288)`

**Comment by nikkothari22** [comment]
Ah it looks like there's an issue with one of the users. Was any user deleted in your site?

**Comment by midhat2020** [comment]
@nikkothari22 Yeah, we had to disable a few individuals who had left the firm, but we were still able to see them in the Raven app's pick contact list, so I had to manually remove them.

**Comment by midhat2020** [comment]
@nikkothari22 I just check by restoring those deleted raven users, but still get the same issue.
